### PR TITLE
Handle lines with multi-byte unicode characters properly

### LINKED ISSUE #10: Carets/offsets are wrong for unicode characters
Using the code:

```python
# -*- coding: utf-8 -*-

1 + "Ĥellö Wörld"
```

leads to

```
Traceback (most recent call last):
  File "C:\Users\ammar\junk\test.py", line 3, in <module>
    1 + "Ĥellö Wörld"
    ^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

### PR DESCRIPTION
**Pull request by ammaraskar**
This should fix #10. To be merged after #9

It converts byte offsets to character offsets in the column numbers so that cases like

```python
raise Exception('clé')
```

are properly printed as

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    raise Exception('clé')
    ^^^^^^^^^^^^^^^^^^^^^^
Exception: clé
```

instead of

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    raise Exception('clé')
    ^^^^^^^^^^^^^^^^^^^^^^^
Exception: clé
```

This also fixes all of the remaining tests, meaning we can start building out the PEP657 tests after this.

### CODE REVIEW

**Comment by isidentical** [comment]
@ammaraskar would you mind rebasing this on top of `bpo-43950` (just merged your fix #9), so that we can proceed.

**Comment by ammaraskar** [comment]
> @ammaraskar would you mind rebasing this on top of `bpo-43950` (just merged your fix #9), so that we can proceed.

Done!

File: Python/traceback.c [hunk 1]
```diff
@@ -563,6 +597,9 @@ tb_displayline(PyTracebackObject* tb, PyObject *f, PyObject *filename, int linen
     }
     
 done:
+    if (source_line) {
+        Py_DECREF(source_line);
+    }
```
Comment (isidentical) [inline Python/traceback.c]: Why not just xdecref?
```suggestion
    Py_XDECREF(source_line);
```

**Review by isidentical — APPROVED** [review]

**Comment by isidentical** [comment]
Thanks Ammar! Later today (in a couple of hours), I'll try to do a final rebase against CPython upstream. Seems like there a couple of changes in the compiler
